name: ANALYSE

# read-write repo token
# access to secrets
on:
  workflow_run:
    workflows: ["PR"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Event info
        run: |
          echo "I am a ${{ github.event_name }} to ${GITHUB_REF#refs/heads/}"
