name: DOCKER

on:
  push:
    # Trigger this workflow on changes to `main`
    branches: [ main ]
    # Trigger this workflow if a semver tag is pushed
    tags: [ 'v*.*.*' ]

env:
  # Will default to docker.io for Docker Hub if empty
  GHC_REGISTRY: ghcr.io
  # github.repository will be <account>/<repo>, for example, DEFRA/gha-docker-demo
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Login against DockerHub
      # https://github.com/docker/login-action
      - name: Log into Docker Hub
        uses: docker/login-action@v1
        with:
          username: cruikshanks
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Login against a Docker registry
      # https://github.com/docker/login-action
      - name: Log into GH Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GHC_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract main metadata (tags, labels) for GHC registry
      # https://github.com/docker/metadata-action
      - name: Extract GH Container Registry metadata
        id: meta_github
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.GHC_REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          target: production
          build-args: |
            GIT_COMMIT=${{ fromJSON(steps.meta_github.outputs.json).labels['org.opencontainers.image.revision'] }}
            DOCKER_TAG=${{ fromJSON(steps.meta_github.outputs.json).tags[0] }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_github.outputs.tags }}
          labels: ${{ steps.meta_github.outputs.labels }}

      # Extract main metadata (tags, labels) for GHC registry
      # https://github.com/docker/metadata-action
      - name: Extract DockerHub Registry metadata
        id: meta_dockerhub
        uses: docker/metadata-action@v3
        with:
          images: docker.io/${{ env.IMAGE_NAME }}

      # Push images to DockerHub
      # TODO: When https://github.com/akhilerm/tag-push-action/issues/88 is resolved remove 'Push latest to DockerHub'
      # step and update `dst:` to just be `dst: ${{ steps.meta_dockerhub.tags }}`
      - name: Push to DockerHub
        uses: akhilerm/tag-push-action@v1.1.0
        with:
          src: ${{ fromJSON(steps.meta_github.outputs.json).tags[0] }}
          dst: ${{ fromJSON(steps.meta_dockerhub.outputs.json).tags[0] }}

      # Currently, though tag-push-action@v1.1.0 says you can pass in multiple tags for the destination it causes it to
      # error. The folks behind it are looking at a solution but till then, we have to pass just one dst at a time. This
      # is our interim solution to also pushing 'latest' to DockerHub when a tag is created.
      # See https://github.com/akhilerm/tag-push-action/issues/88
      - name: Push latest to DockerHub
        uses: akhilerm/tag-push-action@v1.1.0
        if: contains(github.ref, 'tags')
        with:
          src: ${{ fromJSON(steps.meta_github.outputs.json).tags[1] }}
          dst: ${{ fromJSON(steps.meta_dockerhub.outputs.json).tags[1] }}
